language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

services:
  - docker

script:
  - ./travis_runner_script.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "dist/cli"
  skip_cleanup: true
  draft: true
