language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

services:
  - docker

script:
  - ./travis_runner_script.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "dist/cli"
    - "dist/cli-darwin"
    - "dist/cli.exe"
    - "dist/cli.md5"
    - "dist/cli-darwin.md5"
    - "dist/cli.exe.md5"
  skip_cleanup: true
