language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

services:
  - docker

script:
  - ./travis_runner_script.sh


before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "pulkitsharma07"
  - git config --local user.email "avastpulkit@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "dist/cli"
    - "dist/cli-darwin"
    - "dist/cli.exe"
    - "dist/cli.md5"
    - "dist/cli-darwin.md5"
    - "dist/cli.exe.md5"
  skip_cleanup: true
