language: go

go:
  - "1.12"

before_install:
  - go get github.com/mattn/goveralls

env:
  - GO111MODULE=on

services:
  - docker

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - if [[ "$TRAVIS_TAG" != "" ]]; then make build; fi

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "dist/cli"
    - "dist/cli-darwin"
    - "dist/cli.exe"
    - "dist/cli.md5"
    - "dist/cli-darwin.md5"
    - "dist/cli.exe.md5"
  skip_cleanup: true
  on:
    tags: true
